name: frontend
on:
  push:
    branches:
      - main
  pull_request:

env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  LINT_JOB:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
             
    - name: Install dependencies
      run:  npm ci

    - name: Run Lint 
      run: npm run lint
 
  TEST_JOB: 
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run:  npm ci

    - name: Run Lint 
      run: npm run test
